GET http://localhost:3001/api/tasks

###

GET http://localhost:3001/api/users

###

PUT http://localhost:3001/api/tasks/3y87tjHGt0XOMLyp2E8I

{
  "createdBy": "Doe Doe",
  "description": "EDITADO",
  "priority": "Alta",
  "responsible": "Doe Doe",
  "status": "Done",
}