GET http://localhost:3001/api/tasks

###

GET http://localhost:3001/api/users

###

PUT http://localhost:3001/api/tasks/PoFl90GkuNOXLewEuAT1

{
  "createdBy": "Doe Doe",
  "description": "EDITADO",
  "priority": "Alta",
  "responsible": "Doe Doe",
  "status": "Done",
}

###

POST http://localhost:3001/api/tasks

{
  "createdBy": "Doe Doe",
  "description": "EDITADO",
  "priority": "Alta",
  "responsible": "Doe Doe",
  "status": "Done",
  "isBlocked": true
}